### ISSUE TITLE
Uncaught Already initiated when script added in html

### ISSUE THREAD

**Issue by syed-farjana** [fetchify-dev/clicktoaddress-js-examples#2]

**Comment by gs-mancs** [comment]
Hi there,
This is quite intentional, you cannot use the initialise function twice on the same page.
The library is throwing the error, as you're asking it to do something that's against the documentation.

In order to add in the integration to multiple forms on a page, please take a look at the integration example with two forms:
https://github.com/craftyclicks/clicktoaddress-js-examples/blob/master/double.html
